format_version: v1.0
configName: DevBoard
folderName: CelHandheld
frameworkPath: C:\Users\keval\.mcc\HarmonyContent
processor: ATSAMD21G17D
projectName: CelHandheld
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAMD21_DFP\3.6.144\samd21d\atdf\ATSAMD21G17D.atdf
